stages:
- test
- acceptance
- publish

lint:
  image: ruby:2.3
  tags:
  - docker
  script:
  - bundle install --path /cache
  - bundle exec rake metadata_lint lint
validate:
  image: ruby:2.3
  tags:
  - docker
  script:
  - bundle install --path /cache
  - bundle exec rake validate

spec:
  image: ruby:2.3
  tags:
  - docker
  script:
  - bundle install --path /cache
  - bundle exec rake spec

acceptance::minikube:
  variables:
    KUBERNETES_VERSION: 1.6.4
    MINIKUBE_PROFILE: kubernetes-addons-${CI_JOB_ID}
  stage: acceptance
  tags:
  - vagrant
  script:
  # install stuff
  - mkdir -p .bin
  - curl -Lo .bin/minikube https://storage.googleapis.com/minikube/releases/v0.19.1/minikube-linux-amd64
  - curl -Lo .bin/kubectl https://storage.googleapis.com/kubernetes-release/release/v1.6.4/bin/linux/amd64/kubectl
  - chmod +x .bin/minikube .bin/kubectl
  - curl -L https://get.docker.com/builds/Linux/x86_64/docker-1.11.1.tgz | tar xvz -C .bin --strip-components=1
  - export PATH=$PATH:$(pwd)/.bin
  # run tests
  - bundle install
  - bundle exec rake minikube

publish-forge:
  stage: publish
  image: ruby:2.3
  tags:
  - docker
  script:
  - 'echo -e "---\nurl: https://forgeapi.puppetlabs.com\nusername: ${FORGE_USER}\npassword: ${FORGE_PASSWORD}" > ${HOME}/.puppetforge.yml'
  - bundle install --path /cache
  - bundle exec rake module:push
  only:
  - tags
