.test::puppet_module: &test_puppet_module
  stage: test
  tags:
  - docker
  script:
  - cd ${CI_PROJECT_DIR}/puppet
  - bundle install --path /cache
  - cd ${CI_PROJECT_DIR}/puppet/modules/${MODULE_NAME}
  - bundle exec rake test

.acceptance::puppet_module: &acceptance_puppet_module
  stage: acceptance
  tags:
  - ruby-2.3
  - vagrant
  when: manual
  script:
  - cd ${CI_PROJECT_DIR}/puppet/modules/${MODULE_NAME}
  - bundle install
  - gem uninstall vagrant-wrapper
  - bundle exec rake beaker:${BEAKER_TARGET}

# run test for puppet modules
test::puppet_module::aws_ebs:
  <<: *test_puppet_module
  variables:
    MODULE_NAME: aws_ebs

test::puppet_module::calico:
  <<: *test_puppet_module
  variables:
    MODULE_NAME: calico

##etcd
test::puppet_module::etcd:
  <<: *test_puppet_module
  variables:
    MODULE_NAME: etcd
acceptance::puppet_module::etcd::single-node:
  <<: *acceptance_puppet_module
  variables:
    MODULE_NAME: etcd
    BEAKER_TARGET: default
acceptance::puppet_module::etcd::three-node:
  <<: *acceptance_puppet_module
  variables:
    MODULE_NAME: etcd
    BEAKER_TARGET: 3n-cluster

##kubernetes
test::puppet_module::kubernetes:
  <<: *test_puppet_module
  variables:
    MODULE_NAME: kubernetes
acceptance::puppet_module::kubernetes::default:
  <<: *acceptance_puppet_module
  variables:
    MODULE_NAME: kubernetes
    BEAKER_TARGET: default

test::puppet_module::kubernetes_addons:
  <<: *test_puppet_module
  variables:
    MODULE_NAME: kubernetes_addons

test::puppet_module::prometheus:
  <<: *test_puppet_module
  variables:
    MODULE_NAME: prometheus

##tarmak
test::puppet_module::tarmak:
  <<: *test_puppet_module
  variables:
    MODULE_NAME: tarmak
acceptance::puppet_module::tarmak::centos-7-k8s-1.8:
  <<: *acceptance_puppet_module
  variables:
    MODULE_NAME: tarmak
    KUBERNETES_VERSION: 1.8.0
    BEAKER_TARGET: default
acceptance::puppet_module::tarmak::centos-7-k8s-1.7:
  <<: *acceptance_puppet_module
  variables:
    MODULE_NAME: tarmak
    KUBERNETES_VERSION: 1.7.7
    BEAKER_TARGET: default
acceptance::puppet_module::tarmak::centos-7-k8s-1.6-rbac:
  <<: *acceptance_puppet_module
  variables:
    MODULE_NAME: tarmak
    KUBERNETES_VERSION: 1.6.8
    BEAKER_TARGET: default
    KUBERNETES_AUTHORIZATION_MODE: "['RBAC']"
acceptance::puppet_module::tarmak::centos-7-k8s-1.5-rbac:
  <<: *acceptance_puppet_module
  variables:
    MODULE_NAME: tarmak
    KUBERNETES_VERSION: 1.5.6
    BEAKER_TARGET: default
    KUBERNETES_AUTHORIZATION_MODE: "['RBAC']"
acceptance::puppet_module::tarmak::centos-7-k8s-1.6-no-rbac:
  <<: *acceptance_puppet_module
  variables:
    MODULE_NAME: tarmak
    KUBERNETES_VERSION: 1.6.8
    BEAKER_TARGET: default
    KUBERNETES_AUTHORIZATION_MODE: "['ABAC']"
acceptance::puppet_module::tarmak::centos-7-k8s-1.5-no-rbac:
  <<: *acceptance_puppet_module
  variables:
    MODULE_NAME: tarmak
    KUBERNETES_VERSION: 1.5.6
    BEAKER_TARGET: default
    KUBERNETES_AUTHORIZATION_MODE: "['ABAC']"

##vault_client
test::puppet_module::vault_client:
  <<: *test_puppet_module
  variables:
    MODULE_NAME: vault_client
acceptance::puppet_module::vault_client::centos:
  <<: *acceptance_puppet_module
  variables:
    MODULE_NAME: vault_client
    BEAKER_TARGET: default
acceptance::puppet_module::vault_client::ubuntu:
  <<: *acceptance_puppet_module
  variables:
    MODULE_NAME: vault_client
    BEAKER_TARGET: ubuntu_1604_single_node

# run test on golang code
#
test::tarmak::golang:
  stage: test
  tags:
  - docker
  image: golang:1.9
  script:
  - rm -rf /go/src/github.com/jetstack
  - mkdir -p /go/src/github.com/jetstack
  - mv ${CI_PROJECT_DIR} /go/src/github.com/jetstack
  - cd /go/src/github.com/jetstack/tarmak
  - make all
  - mv /go/src/github.com/jetstack/tarmak ${CI_PROJECT_DIR}

# generate sphinx documentation
generate::docs:
  stage: test
  tags:
  - docker
  image: python:2.7
  script:
  - virtualenv -q /cache/venv
  - source /cache/venv/bin/activate
  - pip install -r docs/requirements.txt
  - make -C docs html
  artifacts:
    paths:
    - docs/_build/html
    expire_in: 4 weeks

release::tarmak::golang:
  stage: release
  tags:
  - docker
  image: golang:1.9
  only:
  - tags
  script:
  - curl -sL https://github.com/goreleaser/goreleaser/releases/download/v0.24.0/goreleaser_Linux_x86_64.tar.gz > /tmp/goreleaser.tar.gz
  - echo "8d494e03d6ab6e2e1bcbb795859f3618454078eaeb21906437958b32b332cee4  /tmp/goreleaser.tar.gz" | sha256sum -c
  - cd /usr/local/bin && tar xvfz /tmp/goreleaser.tar.gz goreleaser
  - rm -rf /go/src/github.com/jetstack
  - mkdir -p /go/src/github.com/jetstack
  - mv ${CI_PROJECT_DIR} /go/src/github.com/jetstack
  - cd /go/src/github.com/jetstack/tarmak
  - make all
  - goreleaser
  - mv /go/src/github.com/jetstack/tarmak ${CI_PROJECT_DIR}

stages:
- test
- acceptance
- release
