
stages:
- test
- acceptance

lint:
  image: ruby:2.3
  tags:
  - docker
  script:
  - bundle install --path /cache
  - bundle exec rake metadata_lint lint

validate:
  image: ruby:2.3
  tags:
  - docker
  script:
  - bundle install --path /cache
  - bundle exec rake validate

spec:
  image: ruby:2.3
  tags:
  - docker
  script:
  - mkdir -p ~/.ssh && echo "${SSH_PRIVATE_KEY}" > ~/.ssh/id_rsa && chmod 600 ~/.ssh/id_rsa
  - echo "git.jetstack.net ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIP3g6Syk+FiWj8kTW39jS8i5BTJ0VAuS8BhXnRBXm5//" > ~/.ssh/known_hosts
  - echo "git.jetstack.net ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC7D7wmfWkOCv7AU0ml8bh866VOBFcd+GpJlQ4qS50V7NmYJb9r49zbmEIwA96QUEcYu2ZAXEjJZmdVMifDtWr0HysnDgxZqfzd7hFax33BTCoBQ1G3cWsY6PL+lbzbJ63K00A3yPrj0ha81Sxatgu41ZKQ6SrFOSzvWJSpXodI2BPFG6yPsXE2KJtmRlLlHBNVyyzIWtBcixgrjE+MOMpsOmJT3mWuU/zkFZDDbdKMgSqjhC1CYVhjdBFCtCMUcXcGXej22NBtoYxJN3+h73ymB2OclbhBSVeSyggBhVMpzghNU3sUuwg0K56NYZ2FQG8+5y7KOIWsKuLFqhaHKqLL" >> ~/.ssh/known_hosts
  - echo "git.jetstack.net ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBJhXGTTVqF6wsQMtgr6SnTdX2VkEE6ORVITsuS5yGt/+E18022+vqLJ8cQDqr+zS7t6C+hObFxOlt9+p4q5HWmA=" >> ~/.ssh/known_hosts
  - bundle install --path /cache
  - bundle exec rake spec


.beaker_template: &beaker_definition
  stage: acceptance
  tags:
  - ruby-2.3
  - vagrant
  script:
  - mkdir -p ~/.ssh && echo "${SSH_PRIVATE_KEY}" > ~/.ssh/id_rsa && chmod 600 ~/.ssh/id_rsa
  - echo "git.jetstack.net ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIP3g6Syk+FiWj8kTW39jS8i5BTJ0VAuS8BhXnRBXm5//" > ~/.ssh/known_hosts
  - echo "git.jetstack.net ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC7D7wmfWkOCv7AU0ml8bh866VOBFcd+GpJlQ4qS50V7NmYJb9r49zbmEIwA96QUEcYu2ZAXEjJZmdVMifDtWr0HysnDgxZqfzd7hFax33BTCoBQ1G3cWsY6PL+lbzbJ63K00A3yPrj0ha81Sxatgu41ZKQ6SrFOSzvWJSpXodI2BPFG6yPsXE2KJtmRlLlHBNVyyzIWtBcixgrjE+MOMpsOmJT3mWuU/zkFZDDbdKMgSqjhC1CYVhjdBFCtCMUcXcGXej22NBtoYxJN3+h73ymB2OclbhBSVeSyggBhVMpzghNU3sUuwg0K56NYZ2FQG8+5y7KOIWsKuLFqhaHKqLL" >> ~/.ssh/known_hosts
  - echo "git.jetstack.net ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBJhXGTTVqF6wsQMtgr6SnTdX2VkEE6ORVITsuS5yGt/+E18022+vqLJ8cQDqr+zS7t6C+hObFxOlt9+p4q5HWmA=" >> ~/.ssh/known_hosts
  - bundle install
  - bundle exec rake ${TASK}
  only:
  - master

beaker::centos-7-k8s-1.6:
  <<: *beaker_definition
  only: []
  variables:
    KUBERNETES_VERSION: 1.6.3
    TASK: beaker

beaker::centos-7-k8s-1.5:
  <<: *beaker_definition
  only: []
  variables:
    KUBERNETES_VERSION: 1.5.7
    TASK: beaker

beaker::centos-7-k8s-1.4:
  <<: *beaker_definition
  variables:
    KUBERNETES_VERSION: 1.4.12
    TASK: beaker

beaker::centos-7-k8s-1.3:
  <<: *beaker_definition
  variables:
    KUBERNETES_VERSION: 1.3.10
    TASK: beaker

beaker::ubuntu-1604-k8s-latest:
  <<: *beaker_definition
  variables:
    TASK: beaker:ubuntu_1604_single_node
