# run test on golang code
#
test::tarmak::golang:
  stage: test
  tags:
  - docker
  image: golang:1.9
  script:
  - curl -Lo /usr/local/bin/dep https://github.com/golang/dep/releases/download/v0.3.2/dep-linux-amd64
  - chmod +x /usr/local/bin/dep
  - rm -rf /go/src/github.com/jetstack
  - mkdir -p /go/src/github.com/jetstack
  - mv ${CI_PROJECT_DIR} /go/src/github.com/jetstack
  - cd /go/src/github.com/jetstack/tarmak
  - make all
  - mv /go/src/github.com/jetstack/tarmak ${CI_PROJECT_DIR}

# generate sphinx documentation
generate::docs:
  stage: test
  tags:
  - docker
  image: python:3
  script:
  - apt-get update
  - apt-get install -y python-enchant wbritish
  - pip install virtualenv
  - make -C docs spelling
  - make -C docs linkcheck
  - make -C docs html
  artifacts:
    paths:
    - docs/_build/html
    expire_in: 4 weeks

release::tarmak::puppet_publish_modules:
  stage: release
  tags:
  - docker
  only:
  - tags
  script:
  - cd ${CI_PROJECT_DIR}/puppet
  - bundle install --path /cache
  - echo "${PUPPETFORGE_DATA}" > ~/.puppetforge.yml && chmod 600 ~/.puppetforge.yml
  - bundle exec rake publish_modules

release::tarmak::golang:
  stage: release
  tags:
  - docker
  image: golang:1.9
  only:
  - tags
  script:
  - curl -Lo /usr/local/bin/dep https://github.com/golang/dep/releases/download/v0.3.2/dep-linux-amd64
  - chmod +x /usr/local/bin/dep
  - curl -sL https://github.com/goreleaser/goreleaser/releases/download/v0.24.0/goreleaser_Linux_x86_64.tar.gz > /tmp/goreleaser.tar.gz
  - echo "8d494e03d6ab6e2e1bcbb795859f3618454078eaeb21906437958b32b332cee4  /tmp/goreleaser.tar.gz" | sha256sum -c
  - cd /usr/local/bin && tar xvfz /tmp/goreleaser.tar.gz goreleaser
  - rm -rf /go/src/github.com/jetstack
  - mkdir -p /go/src/github.com/jetstack
  - mv ${CI_PROJECT_DIR} /go/src/github.com/jetstack
  - cd /go/src/github.com/jetstack/tarmak
  - make all
  - goreleaser
  - mv /go/src/github.com/jetstack/tarmak ${CI_PROJECT_DIR}

stages:
- test
- acceptance
- release
