language: go
go:
  - 1.9
before_install:
  - sudo apt-get -qq update
  - sudo apt-get -y install enchant
  - sudo curl -Lo /usr/local/bin/dep https://github.com/golang/dep/releases/download/v0.3.2/dep-linux-amd64
  - sudo chmod +x /usr/local/bin/dep
  # fetch the full git history (otherwise git subtree will fail)
  - git fetch --unshallow
install:
  - make depend
  - make -C docs .venv
script:
  - make all
  - make -C docs spelling
  - make -C docs linkcheck
  - make -C docs html

branches:
  only:
    - master
