# vendor in code gen tools
required = [
  "k8s.io/code-generator/cmd/client-gen",
  "k8s.io/code-generator/cmd/conversion-gen",
  "k8s.io/code-generator/cmd/deepcopy-gen",
  "k8s.io/code-generator/cmd/defaulter-gen",
  "k8s.io/code-generator/cmd/informer-gen",
  "k8s.io/code-generator/cmd/lister-gen",
  "github.com/golang/mock/mockgen",
  "github.com/jteeuwen/go-bindata/go-bindata",
]

[[constraint]]
  name = "github.com/fsouza/go-dockerclient"
  version = "1.0"

[[constraint]]
  branch = "master"
  name = "github.com/hashicorp/go-multierror"

[[constraint]]
  name = "github.com/sirupsen/logrus"
  version = "1.0.0"

[[constraint]]
  branch = "master"
  name = "github.com/spf13/cobra"

[[constraint]]
  branch = "master"
  name = "github.com/spf13/viper"

[[constraint]]
  branch = "v2"
  name = "gopkg.in/yaml.v2"

[[constraint]]
  branch = "master"
  name = "github.com/grpc-ecosystem/go-grpc-prometheus"

[[constraint]]
  name = "github.com/jteeuwen/go-bindata"
  revision = "a0ff2567cfb70903282db057e799fd826784d41d"

[[constraint]]
  name = "github.com/jetstack/vault-unsealer"
  version = "0.2.1"

[[constraint]]
  name = "github.com/jetstack/vault-helper"
  version = "0.9.10"

[[constraint]]
  name = "github.com/cenkalti/backoff"
  version = "1.1.0"

[[constraint]]
  name = "k8s.io/client-go"
  version = "kubernetes-1.9.3"

[[constraint]]
  name = "k8s.io/apimachinery"
  version = "kubernetes-1.9.3"

[[constraint]]
  name = "k8s.io/api"
  version = "kubernetes-1.9.3"

[[constraint]]
  name = "k8s.io/apiserver"
  version = "kubernetes-1.9.3"

[[constraint]]
  name = "k8s.io/code-generator"
  version = "kubernetes-1.9.3"

[[constraint]]
  name = "gopkg.in/src-d/go-git.v4"
  revision = "b08cc8dc5450981530af3e6f6ad1159ae8ea8705"

[[override]]
  name = "github.com/hashicorp/vault"
  version = "0.9.5"

[[override]]
  name = "github.com/opencontainers/runc"
  revision = "a618ab5a0186905949ee463dbb762c3d23e12a80"

[[override]]
  name = "github.com/docker/go-connections"
  revision = "7beb39f0b969b075d1325fecb092faf27fd357b6"

[[constraint]]
  name = "github.com/hashicorp/terraform"
  version = "0.11.7"

[[constraint]]
  name = "github.com/terraform-providers/terraform-provider-aws"
  version = "1.13.0"

[[constraint]]
  name = "github.com/terraform-providers/terraform-provider-random"
  version = "1.2.0"

[[constraint]]
  name = "github.com/terraform-providers/terraform-provider-tls"
  version = "1.1.0"

[[constraint]]
  name = "github.com/terraform-providers/terraform-provider-template"
  version = "1.0.0"

[[constraint]]
  name = "github.com/terraform-providers/terraform-provider-openstack"
  version = "0.1.0"

[[override]]
  name = "github.com/Azure/azure-sdk-for-go"
  version = "10.3.0-beta"

[[override]]
  name = "cloud.google.com/go"
  version = "0.20.0"

[[override]]
  name = "github.com/masterzen/winrm"
  revision = "7e40f93ae939004a1ef3bd5ff5c88c756ee762bb"

[[override]]
  name = "github.com/masterzen/azure-sdk-for-go"
  revision = "ee4f0065d00cd12b542f18f5bc45799e88163b12"

[[override]]
  name = "github.com/gophercloud/gophercloud"
  revision = "3027adb1ce72bc52b87b2decccc7852574b90031"

[[override]]
  name = "github.com/chzyer/readline"
  revision = "c914be64f07d9998f52bf0d598ec26d457168c0f"

[prune]
  non-go = true
  go-tests = true
  unused-packages = true
