sudo: true
language: ruby
cache: bundler
bundler_args: --without system_tests
env:
  global:
    - KUBERNETES_VERSION=1.7.5
    - MINIKUBE_VERSION=0.22.3
  matrix:
    - PUPPET_VERSION='~> 4.10.0' STRICT_VARIABLES=yes
    - PUPPET_VERSION='~> 5.3.0' STRICT_VARIABLES=yes
before_install:
  - bundle -v
  - rm Gemfile.lock || true
  - gem update --system
  - gem update bundler
  - gem --version
  - bundle -v
before_script:
      - set -e
      - curl -Lo kubectl https://storage.googleapis.com/kubernetes-release/release/v$KUBERNETES_VERSION/bin/linux/amd64/kubectl && chmod +x kubectl && sudo mv kubectl /usr/local/bin/
      - curl -Lo minikube https://storage.googleapis.com/minikube/releases/v$MINIKUBE_VERSION/minikube-linux-amd64 && chmod +x minikube && sudo mv minikube /usr/local/bin/
      - sudo chown root /usr/local/bin/minikube
      - sudo chmod u+s /usr/local/bin/minikube
      - sudo chown root /usr/local/bin/kubectl
      - sudo chmod u+s /usr/local/bin/kubectl
      - minikube config set vm-driver none
script: 'bundle exec rake test'
